### PR TITLE
Elasticsearch upgrade

### LINKED ISSUE #175: Error setting schema on ES 7
This won't be an issue until we upgrade to ES 7. 

When I tried to post to an ES 7 index (`es_set_schema`), I got 

```
environment: development
Setting schema: http://127.0.0.1:9200/karinapi/_mapping/_doc?pretty=true
Error: {
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."
  },
  "status" : 400
}

```

### PR DESCRIPTION
**Pull request by wkdewey**
closes #175 and also related to https://github.com/CDRH/api/issues/123. Will result in breaking changes if we add it to the release, it will not be possible to post to Elasticsearch 6 under the present code. We could put a setting in the config file and add some conditional logic, but that could require changes to existing repos

### CODE REVIEW

File: lib/datura/elasticsearch/index.rb [hunk 1]
```diff
@@ -226,7 +229,8 @@ def self.clear_index(options)
 
     if confirmation
       data = self.build_clear_data(options)
-      RestClient.post(url, data.to_json, { content_type: :json }) { |res, req, result|
+      auth_header = Datura::Helpers.construct_auth_header(options)
```
Comment (techgique) [inline lib/datura/elasticsearch/index.rb:234]: Note for future reference on committing. This helper method isn't included in this commit also, so the code would be broken at this commit. It's added in the next commit, but in the future these kinds of things need to be committed together.

**Review by techgique — APPROVED** [review]
Looks good. Merging this into the other branch
